#!/bin/sh

perl -pi -e "s/\\\$NULL\\\$/$1/g" `find . -not -path '*git*' -and -type f`
mv ./src/config.tmpl ./src/$1_config.cfg
rm -rf .git
rm $0
git init
mv pre-commit .git/hooks
git add *
git add .gitignore
git commit -m"Initial commit"
